#!/bin/bash
while [ -n "$1" ]; do
    if [ -r "$1" ]; then
        max_word=""
        max_len=0
        for i in $(strings "$1"); do
            len=$(echo -n "$i" | wc -c)
            if (( len > max_len )); then
                max_len=$len
                max_word=$i
            fi
        done
        echo "$1: '$max_word' ($max_len characters)"
    else
        echo "$1 파일을 읽을 수 없습니다."
    fi
    shift
done
